export const CARDINFO_GET_SUCCESS = 'CARDINFO_GET_SUCCESS'
export const CARDINFO_GET_ERROR = 'CARDINFO_GET_ERROR'
export const CARDINFO_CREATE = 'CARDINFO_CREATE'
export const CARDINFO_SET = 'CARDINFO_SET'

export const CURRENTCARD_GET_SUCCESS = 'CURRENTCARD_GET_SUCCESS'
export const CURRENTCARD_SET = 'CURRENTCARD_SET'